project:
  run_tag: baseline
  name: SNU_LAI_FPAR_natmask_global
  crs: EPSG:4326
  aoi_extent:
    lon_min: 20.0
    lon_max: 140.0
    lat_min: 35.0
    lat_max: 70.0
  years:
    lai_start: 1992.0
    lai_end: 2020.0
    cci_start: 1992.0
    cci_end: 2020.0
    glc_start: 1985.0
    glc_end: 2020.0
  aois:
    india:
      lon_min: 68.0
      lon_max: 98.0
      lat_min: 6.0
      lat_max: 37.0
    china:
      lon_min: 73.0
      lon_max: 135.0
      lat_min: 18.0
      lat_max: 54.0
    south_korea:
      lon_min: 124.0
      lon_max: 131.0
      lat_min: 33.0
      lat_max: 40.0
    switzerland:
      lon_min: 6.0
      lon_max: 11.0
      lat_min: 46.0
      lat_max: 48.0
    usa:
      lon_min: -170.0
      lon_max: -65.0
      lat_min: 18.0
      lat_max: 72.0
    europe:
      lon_min: -25.0
      lon_max: 45.0
      lat_min: 33.0
      lat_max: 72.0
    se_asia:
      lon_min: 92.0
      lon_max: 120.0
      lat_min: -12.0
      lat_max: 23.0
    amazon:
      lon_min: -80.0
      lon_max: -45.0
      lat_min: -20.0
      lat_max: 6.0
    australia_se:
      lon_min: 134.0
      lon_max: 154.0
      lat_min: -40.0
      lat_max: -24.0
    indonesia:
      lon_min: 95.0
      lon_max: 141.0
      lat_min: -11.0
      lat_max: 6.0
    nile_delta:
      lon_min: 28.0
      lon_max: 33.0
      lat_min: 29.0
      lat_max: 32.0
    pampas:
      lon_min: -66.0
      lon_max: -57.0
      lat_min: -39.0
      lat_max: -30.0
    corn_belt:
      lon_min: -105.0
      lon_max: -80.0
      lat_min: 35.0
      lat_max: 49.0
    uk:
      lon_min: -10.0
      lon_max: 3.0
      lat_min: 49.0
      lat_max: 60.0
    west_africa:
      lon_min: -20.0
      lon_max: 20.0
      lat_min: 0.0
      lat_max: 20.0
    global:
      lon_min: -180.0
      lon_max: 180.0
      lat_min: -90.0
      lat_max: 90.0
aois:
  india:
    lon_min: 68.0
    lon_max: 98.0
    lat_min: 6.0
    lat_max: 37.0
  china:
    lon_min: 73.0
    lon_max: 135.0
    lat_min: 18.0
    lat_max: 54.0
  south_korea:
    lon_min: 124.0
    lon_max: 131.0
    lat_min: 33.0
    lat_max: 40.0
  switzerland:
    lon_min: 6.0
    lon_max: 11.0
    lat_min: 46.0
    lat_max: 48.0
  usa:
    lon_min: -170.0
    lon_max: -65.0
    lat_min: 18.0
    lat_max: 72.0
  europe:
    lon_min: -25.0
    lon_max: 45.0
    lat_min: 33.0
    lat_max: 72.0
  se_asia:
    lon_min: 92.0
    lon_max: 120.0
    lat_min: -12.0
    lat_max: 23.0
  amazon:
    lon_min: -80.0
    lon_max: -45.0
    lat_min: -20.0
    lat_max: 6.0
  australia_se:
    lon_min: 134.0
    lon_max: 154.0
    lat_min: -40.0
    lat_max: -24.0
  indonesia:
    lon_min: 95.0
    lon_max: 141.0
    lat_min: -11.0
    lat_max: 6.0
  nile_delta:
    lon_min: 28.0
    lon_max: 33.0
    lat_min: 29.0
    lat_max: 32.0
  pampas:
    lon_min: -66.0
    lon_max: -57.0
    lat_min: -39.0
    lat_max: -30.0
  corn_belt:
    lon_min: -105.0
    lon_max: -80.0
    lat_min: 35.0
    lat_max: 49.0
  uk:
    lon_min: -10.0
    lon_max: 3.0
    lat_min: 49.0
    lat_max: 60.0
  west_africa:
    lon_min: -20.0
    lon_max: 20.0
    lat_min: 0.0
    lat_max: 20.0
  global:
    lon_min: -180.0
    lon_max: 180.0
    lat_min: -90.0
    lat_max: 90.0
paths:
  lai_nc_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/LAI/lai_1982-2021
  fpar_nc_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/FPAR/fpar_1982-2021
  cci_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/ESACCI/ESACCI_1992-2020
  luh2_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/LUH2_v2h
  glc_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/GLC_FCS30D
  valid_tiles_info: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/valid_tiles_info_0p05_full_10deg.rds
  bilinear_ref: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/refgrid_0p05.nc
  ref_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src
  out_root: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline
  georef_lai_0p05_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/georef/georef_lai_0p05
  georef_fpar_0p05_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/georef/georef_fpar_0p05
  cci_out_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/frac/cci_frac_0p05
  cci_quick_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/frac/cci_frac_0p05/quicklooks
  glc_out_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/frac/GLC_frac_0p05
  glc_quick_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data/frac/GLC_frac_0p05/quicklooks
  masks_root_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks
  masks_cci_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_cci
  masks_cci_quick_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_cci/quicklooks
  masks_glc_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_glc
  masks_glc_quick_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_glc/quicklooks
  masks_luh_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_luh
  masks_luh_quick_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masks/mask_luh/quicklooks
  masked_lai_cci_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/LAI/masked_LAI_CCI/masked_lai_0p05
  masked_lai_glc_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/LAI/masked_LAI_GLC/masked_lai_0p05
  masked_fpar_cci_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/FPAR/masked_FPAR_CCI/masked_fpar_0p05
  masked_fpar_glc_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/FPAR/masked_FPAR_GLC/masked_fpar_0p05
  masked_lai_luh_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/LAI/masked_LAI_LUH/masked_lai_0p05
  masked_fpar_luh_005_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p05/FPAR/masked_FPAR_LUH/masked_fpar_0p05
  masked_lai_cci_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/LAI/masked_LAI_CCI/masked_lai_0p25
  masked_lai_glc_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/LAI/masked_LAI_GLC/masked_lai_0p25
  masked_fpar_cci_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/FPAR/masked_FPAR_CCI/masked_fpar_0p25
  masked_fpar_glc_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/FPAR/masked_FPAR_GLC/masked_fpar_0p25
  masked_lai_luh_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/LAI/masked_LAI_LUH/masked_lai_0p25
  masked_fpar_luh_025_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/output/baseline/masked_0p25/FPAR/masked_FPAR_LUH/masked_fpar_0p25
grids:
  grid_005:
    ref_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/ref_0p05.tif
    resolution_deg: 0.05
    extent:
    - -180.0
    - 180.0
    - -90.0
    - 90.0
    area_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/area_0p05_km2.tif
    aoi_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/aoi_0p05.tif
  grid_025:
    ref_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/ref_0p25.tif
    resolution_deg: 0.25
    extent:
    - -180.0
    - 180.0
    - -90.0
    - 90.0
    area_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/area_0p25_km2.tif
    aoi_raster: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/src/aoi_0p25.tif
variables:
  produce:
  - LAI
  - FPAR
  lai:
    nc_var_name_primary: LAI
    nc_var_name_fallback: auto_first_variable
    units: m2 m-2
    clamp:
      min: 0.0
      max: 8.0
    nc_lon_name: lon
    nc_lat_name: lat
    nc_time_names:
    - time
    - time_counter
  fpar:
    nc_var_name_primary: FPAR
    nc_var_name_fallback: auto_first_variable
    units: '1'
    clamp:
      min: 0.0
      max: 1.0
    nc_lon_name: lon
    nc_lat_name: lat
    nc_time_names:
    - time
    - time_counter
resampling:
  categorical: near
  continuous: bilinear
esa_cci:
  version: v2.0.7
  classes:
    nodata: 0.0
    cropland:
    - 10.0
    - 11.0
    - 12.0
    - 20.0
    cls30: 30.0
    cls40: 40.0
    grassland: 130.0
    urban: 190.0
    bare:
    - 200.0
    - 201.0
    - 202.0
    water: 210.0
    snow_ice: 220.0
  mask_window_years:
  - 1992.0
  - 2020.0
  clean_majority_threshold: 0.5
  clean_operator: <=
  weights:
    cls30: 0.75
    cls40: 0.25
glc:
  product: GLC_FCS30D
  tiles_dir: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/GLC_FCS30D
  nodata_in: 0.0
  classes:
    cropland:
    - 10.0
    - 11.0
    - 12.0
    - 20.0
    grassland: 130.0
    urban: 190.0
    bare:
    - 200.0
    - 201.0
    - 202.0
    water: 210.0
    snow_ice: 220.0
    nodata:
    - 0.0
    - 250.0
  years:
  - 1985.0
  - 1990.0
  - 1995.0
  - 2000.0
  - 2001.0
  - 2002.0
  - 2003.0
  - 2004.0
  - 2005.0
  - 2006.0
  - 2007.0
  - 2008.0
  - 2009.0
  - 2010.0
  - 2011.0
  - 2012.0
  - 2013.0
  - 2014.0
  - 2015.0
  - 2016.0
  - 2017.0
  - 2018.0
  - 2019.0
  - 2020.0
  - 2021.0
  - 2022.0
  mask_window_years:
  - 1985.0
  - 2020.0
  clean_majority_threshold: 0.5
  clean_operator: <=
luh2:
  states_nc: /home/akurth@giub.local/GitHub/natural_LAI_FPAR/data-raw/LUH2_v2h/states.nc
  variables:
    cropland_components:
    - c3ann
    - c4ann
    - c3per
    - c4per
    - c3nfx
    pasture: pastr
    pasture_range: range
    urban: urban
thresholds:
  cu_fraction_max_025:
  - 0.03
  - 0.05
  - 0.1
  - 0.2
  baseline_T: 0.05
naming:
  masked005: LAI_{pipeline}_{mask_key}_{yyyymm}_0p05_masked.tif
  masked025: LAI_{pipeline}_{mask_key}_{yyyymm}_0p25_masked.tif
  final025: LAI_{pipeline}_{mask_key}_{yyyymm}_0p25_luh2_T={T}.tif
  T_token_format: 0p%02d
  masked005_fpar: FPAR_{pipeline}_{mask_key}_{yyyymm}_0p05_masked.tif
  masked025_fpar: FPAR_{pipeline}_{mask_key}_{yyyymm}_0p25_masked.tif
  final025_fpar: FPAR_{pipeline}_{mask_key}_{yyyymm}_0p25_luh2_T={T}.tif
